package com.example.smartpantrymanager;

import android.app.DatePickerDialog;import android.os.Bundle;import android.text.InputType;import android.widget.ArrayAdapter;import android.widget.Button;import android.widget.EditText;import android.widget.Spinner;import android.widget.Toast;import androidx.appcompat.app.AppCompatActivity;import java.util.Calendar;

public class AddEditIngredientActivity extends AppCompatActivity{
    private EditText name,quantity,expiry;private Spinner unit;private PantryDataSource dataSource;private long id=-1;
    @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_add_edit_ingredient);id=getIntent().getLongExtra("ingredient_id",-1);name=findViewById(R.id.etName);quantity=findViewById(R.id.etQuantity);expiry=findViewById(R.id.etExpiry);unit=findViewById(R.id.spinnerUnit);dataSource=new PantryDataSource(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"g","kg","ml","L","pcs","can","tbsp","slices","leaves","cloves"});unit.setAdapter(a);expiry.setOnClickListener(v->showDatePicker());findViewById(R.id.btnSave).setOnClickListener(v->save());findViewById(R.id.btnCancel).setOnClickListener(v->finish());if(id>=0)loadItem();setTitle(id>=0?"Edit Ingredient":"Add Ingredient");}
    private void loadItem(){dataSource.open();PantryItem i=dataSource.getIngredient(id);dataSource.close();if(i==null){finish();return;}name.setText(i.getName());quantity.setText(String.valueOf(i.getQuantity()));expiry.setText(i.getExpiryDate());for(int x=0;x<unit.getCount();x++)if(unit.getItemAtPosition(x).toString().equalsIgnoreCase(i.getUnit()))unit.setSelection(x);}
    private void showDatePicker(){Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,d)->expiry.setText(String.format("%04d-%02d-%02d",y,m+1,d)),c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
    private void save(){String n=name.getText().toString().trim();String q=quantity.getText().toString().trim();if(n.isEmpty()){name.setError("Ingredient name is required");return;}if(q.isEmpty()){quantity.setError("Quantity is required");return;}double val;try{val=Double.parseDouble(q);}catch(Exception e){quantity.setError("Enter a valid number");return;}if(val<=0){quantity.setError("Quantity must be greater than zero");return;}PantryItem item=new PantryItem(id,n,val,unit.getSelectedItem().toString(),expiry.getText().toString().trim());dataSource.open();if(id<0)dataSource.insertIngredient(item);else dataSource.updateIngredient(item);dataSource.close();Toast.makeText(this,id<0?"Ingredient added":"Ingredient updated",Toast.LENGTH_SHORT).show();finish();}
}
